import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { containerClass } from '@/styles/tailwind-classes'; 


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
            <div className={containerClass+ ' '}>
                {children}
            </div>
        </body>
        </html>
    );
}
